<a href="https://colab.research.google.com/github/degasbr1964/Tech-Challenge-Fase-1/blob/main/Tech_Challenge_Fase_1_Edgar.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
!pip install xlrd

'pip' nao � reconhecido como um comando interno
ou externo, um programa oper�vel ou um arquivo em lotes.

Como melhorar o NPS das vendas online da empresa. Porque o usuário se torna detrator ou promotor da empresa.

In [6]:
# Libs - bibliotecas de exploração e manipulação de dados
import pandas as pd
import numpy as np

# Libs Gráficas
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px

# Avisos
import warnings
warnings.filterwarnings("ignore")

ModuleNotFoundError: No module named 'pandas'

In [ ]:
nps = pd.read_csv("desafio_nps_fase_1.csv")

In [ ]:
nps.head(20)

,customer_id,customer_age,customer_region,customer_tenure_months,order_id,order_value,items_quantity,discount_value,payment_installments,delivery_time_days,delivery_delay_days,freight_value,delivery_attempts,customer_service_contacts,resolution_time_days,nps_score,repeat_purchase_30d,complaints_count,csat_internal_score
0,1,63,Nordeste,14,50001,139.73,4,39.35,4,2,2,55.53,3,0,4,6.9,0,3,6.5
1,2,20,Sul,1,50002,458.95,2,9.51,10,6,4,28.23,3,0,10,2.4,0,3,0.0
2,3,46,Nordeste,111,50003,507.06,5,42.82,6,6,1,40.99,1,4,5,4.8,0,7,1.5
3,4,52,Centro-Oeste,117,50004,302.19,2,19.58,9,5,2,35.24,3,1,11,5.9,0,4,0.3
4,5,56,Norte,50,50005,253.06,1,29.37,11,13,1,39.32,1,1,0,6.1,0,3,7.9
5,6,35,Sudeste,75,50006,568.76,6,36.58,3,4,5,41.82,2,2,3,0.9,0,5,1.5
6,7,37,Sudeste,68,50007,41.29,3,99.62,6,8,3,35.83,3,3,4,1.4,0,6,0.6
7,8,60,Sul,37,50008,428.76,4,29.54,10,11,5,44.50,1,0,2,0.0,0,2,4.1
8,9,40,Sul,60,50009,121.56,3,91.95,6,6,3,24.88,2,1,9,6.2,0,3,0.8
9,10,51,Sudeste,70,50010,411.01,6,37.47,3,9,2,30.59,1,0,7,2.7,0,2,4.2
10,11,50,Centro-Oeste,28,50011,616.17,2,23.00,8,4,2,52.94,3,0,7,5.3,0,6,2.7
11,12,67,Norte,81,50012,509.48,2,10.42,1,11,1,46.92,2,1,3,7.0,0,2,5.8
12,13,65,Centro-Oeste,85,50013,588.28,6,12.54,5,11,2,28.67,2,1,9,3.7,0,4,0.4
13,14,27,Sudeste,42,50014,165.19,5,52.82,5,10,1,63.92,3,0,8,2.9,0,2,3.5
14,15,50,Sudeste,113,50015,220.81,3,30.73,6,7,3,45.96,1,1,4,2.7,0,3,2.4
15,16,64,Norte,114,50016,732.83,2,13.24,8,9,3,46.78,2,1,8,6.0,0,2,0.0
16,17,50,Norte,70,50017,391.66,4,0.25,11,3,2,59.78,2,1,6,1.9,0,4,2.7
17,18,65,Sul,21,50018,483.04,1,28.08,1,12,3,44.76,2,1,10,4.8,0,4,0.0
18,19,43,Sul,86,50019,383.98,3,33.61,11,3,4,25.24,2,2,3,3.4,0,4,2.0
19,20,37,Centro-Oeste,74,50020,288.93,2,20.80,9,9,2,62.02,1,1,3,2.0,0,4,5.0

# Tamanho da base de dados

In [ ]:
nps.shape

(2500, 19)

In [ ]:
print(f'A base de dados possui {nps.shape[0]} linhas e {nps.shape[1]} colunas')

A base de dados possui 2500 linhas e 19 colunas

Verificar o tipo das colunas

In [ ]:
nps.dtypes

customer_id                    int64
customer_age                   int64
customer_region               object
customer_tenure_months         int64
order_id                       int64
order_value                  float64
items_quantity                 int64
discount_value               float64
payment_installments           int64
delivery_time_days             int64
delivery_delay_days            int64
freight_value                float64
delivery_attempts              int64
customer_service_contacts      int64
resolution_time_days           int64
nps_score                    float64
repeat_purchase_30d            int64
complaints_count               int64
csat_internal_score          float64
dtype: object

Existem valores nulos?

In [ ]:
nps.isnull().sum().sum()

np.int64(0)

Não existem valores nulos

In [ ]:
nps.columns

Index(['customer_id', 'customer_age', 'customer_region',
       'customer_tenure_months', 'order_id', 'order_value', 'items_quantity',
       'discount_value', 'payment_installments', 'delivery_time_days',
       'delivery_delay_days', 'freight_value', 'delivery_attempts',
       'customer_service_contacts', 'resolution_time_days', 'nps_score',
       'repeat_purchase_30d', 'complaints_count', 'csat_internal_score'],
      dtype='object')

Cria uma base com menos colunas

In [ ]:
df_nps = nps[['customer_age', 'customer_region',
       'customer_tenure_months', 'order_value', 'items_quantity',
       'discount_value', 'payment_installments', 'delivery_time_days',
       'delivery_delay_days', 'freight_value', 'delivery_attempts',
       'customer_service_contacts', 'resolution_time_days', 'nps_score',
       'repeat_purchase_30d', 'complaints_count', 'csat_internal_score']]

In [ ]:
df_nps.head()

,idade,regiao,tempo_relacionamento,valor_compra,quantidade,desconto,parcelas,tempo_entrega,dias_atraso,valor_frete,tentativas_entrega,chamados_sac,tempo_resolucao,nps,recompra_30d,num_reclamacoes,csat
0,63,Nordeste,14,139.73,4,39.35,4,2,2,55.53,3,0,4,6.9,0,3,6.5
1,20,Sul,1,458.95,2,9.51,10,6,4,28.23,3,0,10,2.4,0,3,0.0
2,46,Nordeste,111,507.06,5,42.82,6,6,1,40.99,1,4,5,4.8,0,7,1.5
3,52,Centro-Oeste,117,302.19,2,19.58,9,5,2,35.24,3,1,11,5.9,0,4,0.3
4,56,Norte,50,253.06,1,29.37,11,13,1,39.32,1,1,0,6.1,0,3,7.9

##Gerando uma amostra da base inicial

In [3]:
np.random.seed(42)
amostra = df_nps.sample(n=1000, replace=False)

NameError: name 'np' is not defined

In [1]:
amostra.head()

NameError: name 'amostra' is not defined

Valores únicos

In [ ]:
df_nps.nunique()

idade                     52
regiao                     5
tempo_relacionamento     119
valor_compra            2457
quantidade                 6
desconto                2050
parcelas                  11
tempo_entrega             13
dias_atraso                9
valor_frete             1897
tentativas_entrega         3
chamados_sac               8
tempo_resolucao           12
nps                      101
recompra_30d               2
num_reclamacoes           12
csat                      98
dtype: int64

In [ ]:
df_nps.columns = ['idade', 'regiao', 'tempo_relacionamento','valor_compra','quantidade','desconto', 'parcelas','tempo_entrega', 'dias_atraso','valor_frete', 'tentativas_entrega', 'chamados_sac','tempo_resolucao','nps','recompra_30d','num_reclamacoes', 'csat']

Estatística descritiva

In [ ]:
df_nps.describe().round(2)

,idade,tempo_relacionamento,valor_compra,quantidade,desconto,parcelas,tempo_entrega,dias_atraso,valor_frete,tentativas_entrega,chamados_sac,tempo_resolucao,nps,recompra_30d,num_reclamacoes,csat
count,2500.00,2500.00,2500.00,2500.00,2500.00,2500.00,2500.00,2500.00,2500.00,2500.00,2500.00,2500.00,2500.00,2500.00,2500.00,2500.00
mean,43.40,61.32,434.26,3.47,29.75,6.00,8.02,2.19,38.22,2.01,1.52,5.49,4.38,0.09,4.15,2.94
std,14.89,34.48,289.77,1.69,29.23,3.16,3.77,1.45,12.08,0.82,1.23,3.46,2.51,0.28,1.78,2.38
min,18.00,1.00,7.76,1.00,0.02,1.00,2.00,0.00,2.62,1.00,0.00,0.00,0.00,0.00,0.00,0.00
25%,31.00,31.00,220.24,2.00,8.88,3.00,5.00,1.00,29.93,1.00,1.00,2.00,2.60,0.00,3.00,0.70
50%,43.00,62.00,375.52,3.00,20.94,6.00,8.00,2.00,38.50,2.00,1.00,6.00,4.40,0.00,4.00,2.80
75%,56.00,91.00,577.29,5.00,40.83,9.00,11.00,3.00,46.27,3.00,2.00,8.00,6.10,0.00,5.00,4.80
max,69.00,119.00,1983.81,6.00,230.33,11.00,14.00,8.00,76.13,3.00,7.00,11.00,10.00,1.00,11.00,10.00

In [ ]:
# funçao classifica NPS

def nps_class(df_nps):
  if df_nps <= 6:
    return "Detrator"
  elif df_nps >= 9:
    return "Promotor"
  else:
    return "Passivo"

Classificação do cliente segundo o NPS
(fonte: Bain & Company)

*   Promotores (9-10)
*   Passivos (7-8)
*   Detratores (0-6)

In [ ]:
df_nps.head()

,idade,regiao,tempo_relacionamento,valor_compra,quantidade,desconto,parcelas,tempo_entrega,dias_atraso,valor_frete,tentativas_entrega,chamados_sac,tempo_resolucao,nps,recompra_30d,num_reclamacoes,csat
0,63,Nordeste,14,139.73,4,39.35,4,2,2,55.53,3,0,4,6.9,0,3,6.5
1,20,Sul,1,458.95,2,9.51,10,6,4,28.23,3,0,10,2.4,0,3,0.0
2,46,Nordeste,111,507.06,5,42.82,6,6,1,40.99,1,4,5,4.8,0,7,1.5
3,52,Centro-Oeste,117,302.19,2,19.58,9,5,2,35.24,3,1,11,5.9,0,4,0.3
4,56,Norte,50,253.06,1,29.37,11,13,1,39.32,1,1,0,6.1,0,3,7.9

## *Função para classificar NPS*

In [ ]:
df_nps['classificacao_nps'] = df_nps['nps'].apply(nps_class)

In [ ]:
df_nps.head()

,idade,regiao,tempo_relacionamento,valor_compra,quantidade,desconto,parcelas,tempo_entrega,dias_atraso,valor_frete,tentativas_entrega,chamados_sac,tempo_resolucao,nps,recompra_30d,num_reclamacoes,csat,classificacao_nps
0,63,Nordeste,14,139.73,4,39.35,4,2,2,55.53,3,0,4,6.9,0,3,6.5,Passivo
1,20,Sul,1,458.95,2,9.51,10,6,4,28.23,3,0,10,2.4,0,3,0.0,Detrator
2,46,Nordeste,111,507.06,5,42.82,6,6,1,40.99,1,4,5,4.8,0,7,1.5,Detrator
3,52,Centro-Oeste,117,302.19,2,19.58,9,5,2,35.24,3,1,11,5.9,0,4,0.3,Detrator
4,56,Norte,50,253.06,1,29.37,11,13,1,39.32,1,1,0,6.1,0,3,7.9,Passivo

In [ ]:
df_nps['recompra_30d'].value_counts()

recompra_30d
0    2282
1     218
Name: count, dtype: int64

### Análise de médias por classificação de NPS para identificar motivos de NPS baixo

In [ ]:
nps_grouped_analysis = df_nps.groupby('classificacao_nps').mean(numeric_only=True).round(2)
display(nps_grouped_analysis.sort_values(by='nps'))

,idade,tempo_relacionamento,valor_compra,quantidade,desconto,parcelas,tempo_entrega,dias_atraso,valor_frete,tentativas_entrega,chamados_sac,tempo_resolucao,nps,recompra_30d,num_reclamacoes,csat
classificacao_nps,,,,,,,,,,,,,,,,
Detrator,43.31,61.58,428.99,3.49,29.63,5.97,8.00,2.53,38.40,1.99,1.69,5.79,3.26,0.0,4.62,2.34
Passivo,43.65,60.11,445.47,3.35,29.53,6.17,8.13,1.29,37.82,2.02,1.09,4.79,7.16,0.2,2.91,4.37
Promotor,43.63,63.00,468.08,3.64,32.75,5.81,7.94,0.72,37.05,2.15,0.67,3.70,9.61,1.0,2.27,6.04

Com a tabela acima, podemos comparar as médias de diversas métricas para cada grupo de NPS. Fatores com valores significativamente maiores para 'Detrator' e menores para 'Promotor' são os potenciais maiores motivadores de um NPS baixo.

Quanto maior os dias de atraso, o tempo de resolução, os chamados ao SAC, o número de reclamações, menor o NPS e consequentemente torna esses clientes detratores da empresa.

In [ ]:
pedidos_atrasados_por_regiao = df_nps[df_nps['dias_atraso'] > 0].groupby('regiao').size().reset_index(name='pedidos_atrasados')
display(pedidos_atrasados_por_regiao)

         regiao  pedidos_atrasados
0  Centro-Oeste                410
1      Nordeste                437
2         Norte                445
3       Sudeste                473
4           Sul                458

Como podemos ver, os atrasos de entrega independem da regiaão, portanto não é um problema localizado, e sim da logística como um todo.

In [ ]:
detratores_com_atraso = df_nps[(df_nps['classificacao_nps'] == 'Detrator') & (df_nps['dias_atraso'] > 0)]
num_detratores_com_atraso = detratores_com_atraso.shape[0]
print(f"O número de Detratores que tiveram atraso na entrega é: {num_detratores_com_atraso}")

O número de Detratores que tiveram atraso na entrega é: 1750

In [ ]:
detratores_com_reclamacao = df_nps[(df_nps['classificacao_nps'] == 'Detrator') & (df_nps['num_reclamacoes'] > 0)]
num_detratores_com_reclamacao = detratores_com_reclamacao.shape[0]
print(f"O número de Detratores que fizeram reclamação é: {num_detratores_com_reclamacao}")

O número de Detratores que fizeram reclamação é: 1850

In [ ]:
total_detratores = df_nps[df_nps['classificacao_nps'] == 'Detrator'].shape[0]
detratrores_atraso_reclamacao = df_nps[(df_nps['classificacao_nps'] == 'Detrator') & (df_nps['dias_atraso'] > 0) & (df_nps['num_reclamacoes'] > 0)]
num_detratores_atraso_reclamacao = detratrores_atraso_reclamacao.shape[0]

if total_detratores > 0:
    porcentagem_detratores_atraso_reclamacao = (num_detratores_atraso_reclamacao / total_detratores) * 100
    print(f"Do total de Detratores, {porcentagem_detratores_atraso_reclamacao:.2f}% tiveram atraso na entrega e fizeram reclamação.")
else:
    print("Não há detratores na base de dados para realizar o cálculo.")

Do total de Detratores, 94.54% tiveram atraso na entrega e fizeram reclamação.

94,54% dos clientes que tiveram atraso na entrega, fizeram reclamação ao SAC, isso nos leva a acreditar que diminuindo os problemas de logística diminuiremos os atendimentos no SAC.

In [ ]:
detratores_reclamacao_sem_atraso = df_nps[(df_nps['classificacao_nps'] == 'Detrator') & (df_nps['num_reclamacoes'] > 0) & (df_nps['dias_atraso'] == 0)]
num_detratores_reclamacao_sem_atraso = detratores_reclamacao_sem_atraso.shape[0]
print(f"O número de Detratores que fizeram reclamação e não tiveram atraso na entrega é: {num_detratores_reclamacao_sem_atraso}")

O número de Detratores que fizeram reclamação e não tiveram atraso na entrega é: 100

Os detratores que não tiveram problemas na entrega é pequeno, e pode ser tratado por um atendimento personalizado para descobrir o que motivou isso.

In [ ]:
promotores_com_atraso = df_nps[(df_nps['classificacao_nps'] == 'Promotor') & (df_nps['dias_atraso'] > 0)]
num_promotores_com_atraso = promotores_com_atraso.shape[0]
print(f"O número de Promotores que tiveram atraso na entrega é: {num_promotores_com_atraso}")

O número de Promotores que tiveram atraso na entrega é: 60